# Import Library & Data

In [ ]:
import pandas as pd

In [ ]:
lab_feb = pd.read_csv('LAB_FEB.csv')

In [ ]:
lab_feb

,TGL_INPUT,NO_REG,NM_PARAM,NM_PERIKSA,HASIL,N_RUJUKAN,MIN_RUJUKAN,MAX_RUJUKAN,FLAG,SATUAN
0,2/2/2026 10:10,10585507,MCHC,Operasi,NaN,32-36,32.0,36.0,NaN,pg
1,2/2/2026 10:10,10585507,MCH,Operasi,NaN,27-34,27.0,34.0,NaN,fl
2,2/2/2026 10:10,10585507,MCV,Operasi,NaN,80-100,80.0,100.0,NaN,fl
3,2/2/2026 10:10,10585507,WBC,Operasi,NaN,4-11,4.0,11.0,NaN,/mm3
4,2/2/2026 10:10,10585507,Neutrofil%,Operasi,NaN,51-67,51.0,67.0,NaN,%
...,...,...,...,...,...,...,...,...,...,...
17617,2/28/2026 23:46,10600260,MCHC,Hematologi Rutin,33.3,32 - 36,31.0,36.0,0.0,pg
17618,2/28/2026 23:46,10600260,PLT,Hematologi Rutin,206,150 - 450,150.0,450.0,0.0,sel/mm3
17619,2/28/2026 23:46,10600260,Lymfosit%,Hematologi Rutin,5.0,20 - 35,20.0,35.0,NaN,%
17620,2/28/2026 23:46,10600260,MXD%,Hematologi Rutin,2.8,0-11,0.0,11.0,0.0,%
17621,2/28/2026 23:46,10600260,Neutrofil%,Hematologi Rutin,92.2,51 - 67,51.0,67.0,4.0,%

In [ ]:
lab_maret = pd.read_csv('LAB_MARET.csv')

In [ ]:
lab_maret

,TGL_INPUT,NO_REG,NM_PARAM,NM_PERIKSA,HASIL,N_RUJUKAN,MIN_RUJUKAN,MAX_RUJUKAN,FLAG,SATUAN
0,3/5/2026 8:16,10588592,Creatinin,Ureum,NaN,0.5-1.4,NaN,NaN,NaN,md/dl
1,3/2/2026 10:33,10595774,MCHC,Operasi,NaN,32-36,32.0,36.0,NaN,pg
2,3/2/2026 10:33,10595774,MCH,Operasi,NaN,27-34,27.0,34.0,NaN,fl
3,3/2/2026 10:33,10595774,MCV,Operasi,NaN,80-100,80.0,100.0,NaN,fl
4,3/2/2026 10:33,10595774,WBC,Operasi,NaN,4-11,4.0,11.0,NaN,/mm3
...,...,...,...,...,...,...,...,...,...,...
20443,3/31/2026 22:44,10611190,Glukosa Darah Sewaktu,Cek Lab Paket Operasi 1,142,70-110,74.0,106.0,4.0,mg/dl
20444,3/31/2026 23:31,10609103,IgM Anti Dengue,Anti Dengue IgG dan IgM,Negatif,NEGATIVE,0.0,0.0,NaN,-
20445,3/31/2026 23:31,10609103,HCT,"AT, HMT",32.0,42-52,42.0,52.0,NaN,vol%
20446,3/31/2026 23:31,10609103,IgG Anti Dengue,Anti Dengue IgG dan IgM,Negatif,NEGATIVE,0.0,0.0,NaN,-
20447,3/31/2026 23:31,10609103,PLT,"AT, HMT",47,150 - 450,150.0,450.0,5.0,sel/mm3

In [ ]:
lab_april = pd.read_csv('LAB_APRIL.csv')

In [ ]:
lab_april

,TGL_INPUT,NO_REG,NM_PARAM,NM_PERIKSA,HASIL,N_RUJUKAN,MIN_RUJUKAN,MAX_RUJUKAN,FLAG,SATUAN
0,4/1/2026 16:38,10603259,PA,Histopatologi,NaN,NaN,NaN,NaN,NaN,NaN
1,4/2/2026 9:50,10605740,PA,Histopatologi,NaN,NaN,NaN,NaN,NaN,NaN
2,4/2/2026 16:40,10605635,PA,Histopatologi,NaN,NaN,NaN,NaN,NaN,NaN
3,4/1/2026 8:45,10608729,PA,Histopatologi,NaN,NaN,NaN,NaN,NaN,NaN
4,4/9/2026 9:26,10609179,PA,Histopatologi,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
18022,4/29/2026 13:22,10622394,Neutrofil%,Hematologi Rutin,75.2,51 - 67,51.0,67.0,4.0,%
18023,4/29/2026 13:42,10621924,Creatinin,Creatinin,3.29,0.9-1.3,0.9,1.3,4.0,mg/dl
18024,4/29/2026 13:42,10621924,Ureum,Ureum,54,17-43,NaN,NaN,NaN,mg/dl
18025,4/29/2026 13:42,10621924,Glukosa Darah Sewaktu,Glukosa Sewaktu,350,70-110,74.0,106.0,4.0,mg/dl
18026,4/29/2026 13:45,10621924,Creatinin,Ureum,NaN,0.5-1.4,NaN,NaN,NaN,md/dl

## Merge Ketiga Tabel

In [ ]:
lab_feb.columns
lab_maret.columns
lab_april.columns

Index(['TGL_INPUT', 'NO_REG', 'NM_PARAM', 'NM_PERIKSA', 'HASIL', 'N_RUJUKAN',
       'MIN_RUJUKAN', 'MAX_RUJUKAN', 'FLAG', 'SATUAN'],
      dtype='object')

In [ ]:
df_lab_all = pd.concat([lab_feb, lab_maret, lab_april], ignore_index=True)

In [ ]:
df_lab_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56097 entries, 0 to 56096
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TGL_INPUT    56097 non-null  object
 1   NO_REG       56097 non-null  int64
 2   NM_PARAM     56097 non-null  object
 3   NM_PERIKSA   56097 non-null  object
 4   HASIL        54813 non-null  object
 5   N_RUJUKAN    54561 non-null  object
 6   MIN_RUJUKAN  50791 non-null  float64
 7   MAX_RUJUKAN  50791 non-null  float64
 8   FLAG         32401 non-null  float64
 9   SATUAN       54280 non-null  object
dtypes: float64(3), int64(1), object(6)
memory usage: 4.3+ MB

In [ ]:
df_lab_all.to_csv('df_lab_all.csv', index=False)

# Assessing Data

In [ ]:
df_lab_all.isna().sum()

TGL_INPUT          0
NO_REG             0
NM_PARAM           0
NM_PERIKSA         0
HASIL           1284
N_RUJUKAN       1536
MIN_RUJUKAN     5306
MAX_RUJUKAN     5306
FLAG           23696
SATUAN          1817
dtype: int64

In [ ]:
lab_feb.duplicated().sum()

np.int64(0)

# Cleaning Data

In [ ]:
df_lab_all['NM_PERIKSA'].nunique()

57

In [ ]:
df_lab_all['NM_PARAM'] = df_lab_all['NM_PARAM'].str.strip().str.lower()
df_lab_all['NM_PERIKSA'] = df_lab_all['NM_PERIKSA'].str.strip().str.lower()
df_lab_all['TGL_INPUT'] = pd.to_datetime(df_lab_all['TGL_INPUT'])

In [ ]:
lab_pivot_all = df_lab_all.pivot_table(
    index=['NO_REG', 'TGL_INPUT', 'NM_PERIKSA'],
    columns='NM_PARAM',
    values='HASIL',
    aggfunc='first'
).reset_index()

In [ ]:
lab_pivot_all.shape

(9118, 112)

In [ ]:
lab_pivot_all

NM_PARAM,NO_REG,TGL_INPUT,NM_PERIKSA,aa do2,albumin,amilum,amoeba,amphetamine,anti hcv,asam urat,...,thc,trigliserida,troponin i high sensitive,tsh,tubex tf,ureum,urine protein,urobilinogen,warna,wbc
0,10254626,2026-02-25 19:24:00,cek lab paket operasi 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
1,10541000,2026-03-11 12:49:00,cek lab paket operasi 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,50,NaN,NaN,NaN,13.6
2,10564221,2026-04-23 12:36:00,cek lab paket operasi 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.3
3,10574561,2026-02-16 17:13:00,cek lab paket operasi 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,39,NaN,NaN,NaN,9.3
4,10579846,2026-02-03 16:22:00,urin lengkap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Negatif,0.2,KUNING,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9113,10622394,2026-04-29 13:22:00,creatinin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9114,10622394,2026-04-29 13:22:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,51,NaN,NaN,NaN,NaN
9115,10622394,2026-04-29 13:22:00,glukosa sewaktu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9116,10622394,2026-04-29 13:22:00,hematologi rutin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.8
9117,10622394,2026-04-29 13:22:00,faal hati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
lab_pivot_all.duplicated(subset=['NO_REG', 'TGL_INPUT', 'NM_PERIKSA']).sum()

np.int64(0)

In [ ]:
lab_pivot_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9118 entries, 0 to 9117
Columns: 112 entries, NO_REG to wbc
dtypes: datetime64[ns](1), int64(1), object(110)
memory usage: 7.8+ MB

In [ ]:
lab_pivot_all['NM_PERIKSA'].value_counts()

NM_PERIKSA
hematologi rutin                                   1905
creatinin                                           985
ureum                                               891
glukosa sewaktu                                     820
urin lengkap                                        630
faal hati                                           491
hemoglobin                                          450
cek lab paket operasi 1                             435
lemak                                               227
at, hmt                                             213
faal ginjal                                         200
cek lab paket operasi 2                             156
hbsag                                               154
paket vk + goldar                                   153
3 parameter ( na, k, cl )                           141
ldl kolesterol direk                                110
bilirubin                                           108
glukosa puasa                                       106
hba1c                                                87
analisa faeces                                       81
tes kehamilan kualitatif                             78
hdl kolesterol direk                                 78
anti hiv                                             70
tshs                                                 60
golongan darah dan rhesus                            56
troponin i                                           56
ft4                                                  55
analisa gas darah (agd)                              51
hepatitis                                            36
narkoba                                              33
igm leptospira                                       29
paket vk                                             21
glukosa 2 jam pp                                     17
cek lab paket operasi 1 tanpa dr                     16
albumin                                              16
widal                                                15
leukosit                                             13
waktu protombin / ppt/ inr                           12
paket protein (protein total, albumin,globulin)       8
hematologi rutin + led                                8
waktu pembekuan                                       7
tubex tf                                              6
elektrolit                                            5
anti dengue igg dan igm                               4
cek lab paket operasi 2 tanpa dr                      4
protein urin                                          4
sputum bta (zn)                                       3
waktu pendarahan                                      3
ppt                                                   2
led/ked                                               2
benzodiazepine (bez)                                  2
gambaran darah tepi / mdt                             2
trombosit                                             1
calcium                                               1
asto kuantitatif                                      1
Name: count, dtype: int64

In [ ]:
#lab_pivot_all.to_csv('lab_pivot_all.csv', index=False)

# Feature Selection

In [ ]:
target_tests = [
    'hematologi rutin',
    'creatinin',
    'ureum',
    'glukosa sewaktu',
    'hemoglobin'
]

In [ ]:
valid_patients = lab_pivot_all[lab_pivot_all['NM_PERIKSA'].isin(target_tests)]['NO_REG'].unique()

In [ ]:
lab_pivot_filtered = lab_pivot_all[lab_pivot_all['NO_REG'].isin(valid_patients)].copy()

In [ ]:
lab_pivot_filtered

NM_PARAM,NO_REG,TGL_INPUT,NM_PERIKSA,aa do2,albumin,amilum,amoeba,amphetamine,anti hcv,asam urat,...,thc,trigliserida,troponin i high sensitive,tsh,tubex tf,ureum,urine protein,urobilinogen,warna,wbc
5,10579978,2026-02-05 09:14:00,urin lengkap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Negatif,0.2,KUNING,NaN
6,10579978,2026-02-05 09:14:00,creatinin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,10579978,2026-02-05 09:14:00,faal ginjal,NaN,NaN,NaN,NaN,NaN,NaN,9.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10579978,2026-02-05 09:14:00,glukosa puasa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10579978,2026-02-05 09:14:00,lemak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9113,10622394,2026-04-29 13:22:00,creatinin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9114,10622394,2026-04-29 13:22:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,51,NaN,NaN,NaN,NaN
9115,10622394,2026-04-29 13:22:00,glukosa sewaktu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9116,10622394,2026-04-29 13:22:00,hematologi rutin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.8
9117,10622394,2026-04-29 13:22:00,faal hati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
numeric_cols = lab_pivot_filtered.columns.drop(['NO_REG', 'TGL_INPUT', 'NM_PERIKSA'])
for col in numeric_cols:
    lab_pivot_filtered[col] = pd.to_numeric(lab_pivot_filtered[col], errors='coerce')

df_final_lab = lab_pivot_filtered.groupby('NO_REG').max().reset_index()

In [ ]:
df_final_lab

NM_PARAM,NO_REG,TGL_INPUT,NM_PERIKSA,aa do2,albumin,amilum,amoeba,amphetamine,anti hcv,asam urat,...,thc,trigliserida,troponin i high sensitive,tsh,tubex tf,ureum,urine protein,urobilinogen,warna,wbc
0,10579978,2026-02-05 09:14:00,urin lengkap,NaN,NaN,NaN,NaN,NaN,NaN,9.32,...,NaN,207.0,NaN,NaN,NaN,24.0,NaN,0.2,NaN,NaN
1,10580957,2026-02-06 09:06:00,lemak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,205.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10581496,2026-02-06 19:25:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,67.0,NaN,NaN,NaN,NaN
3,10582858,2026-02-03 11:56:00,lemak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10583233,2026-02-11 18:19:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,75.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2462,10622311,2026-04-29 09:39:00,hematologi rutin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
2463,10622354,2026-04-29 11:09:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,NaN,8.4
2464,10622360,2026-04-29 11:33:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,32.0,NaN,NaN,NaN,6.9
2465,10622389,2026-04-29 12:42:00,urin lengkap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,9.6
2466,10622394,2026-04-29 13:22:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,51.0,NaN,NaN,NaN,8.8

In [ ]:
df_final_lab.to_csv('df_lab_selected.csv', index=False)